language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
# mock is already installed on travis
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
script:
  - coverage run ./setup.py test
after_success:
  - coveralls
